name: '[Workflow] Build and Publish Docker Image'

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**

permissions:
  contents: read

jobs:
  setup-build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      image_tag: ${{ steps.semver_tag.outputs.created_tag }}
    steps:
      - name: Bump version and push tag
        uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@v2.7.3
        id: semver_tag
        env:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          default_bump: 'patch'

  build-publish:
    uses: ./.github/workflows/_build_go.yml
    needs: setup-build-publish
    permissions:
      security-events: write
    with:
      tags: ${{ needs.setup-build-publish.outputs.image_tag }},latest
      ecr_repository: shared/php-fpm-stats-exporter
      push: true
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
