name: '[Workflow] Pull Request'

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  pull_request_labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

  docker:
    uses: ./.github/workflows/_build_go.yml
    with:
      tags: ${{ github.event.pull_request.head.sha }}
      ecr_repository: shared/php-fpm-stats-exporter
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
